import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from './components/navigation/Navigation'
import Footer from './components/footer/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Get Linked',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className} style={{padding: 'lg:px-24 px-4'}}>
        <div className='bg-main_bg bg-repeat-y font-montserrat text-white'>
        <Navbar />
        {children}
        </div>
        </body>
          
    </html>
  )
}
